version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/circleci/nginx-proxy/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
