version: '2'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy

  docker-gen:
    container_name: nginx-proxy-gen
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./etc/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen'
    networks:
      - proxy

  acme-companion:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=jhs851767@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  proxy:
    driver: bridge
    external: true