# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@2.0.0

workflows:
  deploy-workflow:
    jobs:
      - aws-code-deploy/deploy:
          application-name: nginx-proxy
          bundle-bucket: nginx-proxy-deploy
          deployment-group: default
          bundle-key: nginx-proxy-zip
          service-role-arn: hyungseok